apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnetapp-dev
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
      - "test.architect4hire.com"
  rules:
  - host: "test.architect4hire.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-aks-app-service
            port:
              number: 4000